INSERT INTO new_tehnorent.news (title, ua_title, alias, description, ua_description, text, ua_text, picture, picture_small, active) VALUES ('прапра', 'прапраар', '', 'прапрапр', 'прапрапр', 'апрарапрапаыва', '', null, null, 'yes');
INSERT INTO new_tehnorent.news (title, ua_title, alias, description, ua_description, text, ua_text, picture, picture_small, active) VALUES ('апвпва', 'пвапва', 'apvpva', 'пвапвапва', 'пвпва', 'пвапвп', 'впвапва', null, null, 'yes');
INSERT INTO new_tehnorent.news (title, ua_title, alias, description, ua_description, text, ua_text, picture, picture_small, active) VALUES ('пвапа папа авпваав', 'ааыва ваывыа', 'pvapa-papa-avpvaav', 'ваыаы ваыаыа', 'ваыв ваыавыа', 'ва ва апвапвап', 'апавпвап апвапвапв', null, null, 'yes');
INSERT INTO new_tehnorent.news (title, ua_title, alias, description, ua_description, text, ua_text, picture, picture_small, active) VALUES ('Тестовая новость №1', 'Тестова новина №1', 'testovaya-novost-1', 'Тестовая новость №1', 'Тестова новина №1', 'Тестовая новость №1', 'Тестова новина №1', null, null, 'yes');
INSERT INTO new_tehnorent.news (title, ua_title, alias, description, ua_description, text, ua_text, picture, picture_small, active) VALUES ('Тестовая новость №2', 'Тестова новина №2', 'testovaya-novost-2', 'Тестовая новость №2', 'Тестова новина №2', 'Тестовая новость №2', 'Тестова новина №2', null, null, 'no');
INSERT INTO new_tehnorent.news (title, ua_title, alias, description, ua_description, text, ua_text, picture, picture_small, active) VALUES ('Тестовая новость №3', 'Тестова новина №3', 'testovaya-novost-3', 'Тестовая новость №3', 'Тестова новина №3', '', '', null, null, 'yes');
INSERT INTO new_tehnorent.news (title, ua_title, alias, description, ua_description, text, ua_text, picture, picture_small, active) VALUES ('авпвапва', 'пвапвап', 'avpvapva', 'вапва', 'пвапва', 'пвавпв', 'пвпвпва', '"20170317-5708_Tulips.jpg"', null, 'yes');
INSERT INTO new_tehnorent.news (title, ua_title, alias, description, ua_description, text, ua_text, picture, picture_small, active) VALUES ('авпвапва', 'пвапвап', 'avpvapva', 'вапва', 'пвапва', 'пвавпв', 'пвпвпва', '"20170317-5718_Tulips.jpg"', null, 'yes');
INSERT INTO new_tehnorent.news (title, ua_title, alias, description, ua_description, text, ua_text, picture, picture_small, active) VALUES ('авпвапва', 'пвапвап', 'avpvapva', 'вапва', 'пвапва', 'пвавпв', 'пвпвпва', '"20170317-5756_Tulips.jpg"', null, 'yes');
INSERT INTO new_tehnorent.news (title, ua_title, alias, description, ua_description, text, ua_text, picture, picture_small, active) VALUES ('рапрар', 'рпрапра', 'raprar', 'арпрарар', 'апрарап', 'апррарап', 'апрапрапапра', '"20170317-5828_Penguins.jpg"', null, 'yes');
INSERT INTO new_tehnorent.news (title, ua_title, alias, description, ua_description, text, ua_text, picture, picture_small, active) VALUES ('Тестовая новость №4', 'Тестова новина №4', 'testovaya-novost-4', 'Тестовая новость №4', 'Тестова новина №4', 'Тестовая новость №4
Тестовая новость №4

Тестовая новость №4Тестовая новость №4', 'Тестова новина №4', '"20170317-0113_Koala.jpg"', null, 'yes');
INSERT INTO new_tehnorent.news (title, ua_title, alias, description, ua_description, text, ua_text, picture, picture_small, active) VALUES ('апопрорпо', 'оопропр', 'apoprorpo', 'пропропо', 'опропроп', 'пропропр', 'пропропропр', '', null, 'yes');
INSERT INTO new_tehnorent.news (title, ua_title, alias, description, ua_description, text, ua_text, picture, picture_small, active) VALUES ('лллллллллллллллллллоро па п ап п а', 'ап а а па па', 'llllllllllllllllllloro-pa-p-ap-p-a', 'па а па а', 'папап па', 'па ап п а', 'а п а', '', null, 'yes');