INSERT INTO new_tehnorent.category (p_id, name, seo, ua_name, ua_seo, active) VALUES (1, 'Шлифовальные и режущие инструменты', '', 'Шліфувальні і ріжучі інструменти', '', 'yes');
INSERT INTO new_tehnorent.category (p_id, name, seo, ua_name, ua_seo, active) VALUES (2, 'Пилы цепные бензиновые', '', 'Пили ланцюгові бензинові', '', 'yes');
INSERT INTO new_tehnorent.category (p_id, name, seo, ua_name, ua_seo, active) VALUES (2, 'Угловые шлифовальные машины', '', 'Кутові шліфувальні машини', '', 'yes');
INSERT INTO new_tehnorent.category (p_id, name, seo, ua_name, ua_seo, active) VALUES (2, 'Пилы цепные  электрические', '', 'Пили ланцюгові електричні', '', 'yes');
INSERT INTO new_tehnorent.category (p_id, name, seo, ua_name, ua_seo, active) VALUES (2, 'Штроборезы', '', 'Штроборізи', '', 'yes');
INSERT INTO new_tehnorent.category (p_id, name, seo, ua_name, ua_seo, active) VALUES (2, 'Ленточные шлифовальные машины', '', 'Стрічкові шліфувальні машини', '', 'yes');
INSERT INTO new_tehnorent.category (p_id, name, seo, ua_name, ua_seo, active) VALUES (2, 'Вибрационные шлифовальные машины', '', 'Вібраційні шліфувальні машини', '', 'yes');
INSERT INTO new_tehnorent.category (p_id, name, seo, ua_name, ua_seo, active) VALUES (2, 'Пилы  торцевые', '', 'Пили торцеві', '', 'yes');
INSERT INTO new_tehnorent.category (p_id, name, seo, ua_name, ua_seo, active) VALUES (2, 'Пилы  дисковые', '', 'Пилки дискові', '', 'yes');
INSERT INTO new_tehnorent.category (p_id, name, seo, ua_name, ua_seo, active) VALUES (2, 'Электролобзики', '', 'Електролобзики', '', 'yes');
INSERT INTO new_tehnorent.category (p_id, name, seo, ua_name, ua_seo, active) VALUES (2, 'Сабельные  пилы', '', 'Шабельні пили', '', 'yes');
INSERT INTO new_tehnorent.category (p_id, name, seo, ua_name, ua_seo, active) VALUES (2, 'Электрорубанки', '', 'Електрорубанки', '', 'yes');
INSERT INTO new_tehnorent.category (p_id, name, seo, ua_name, ua_seo, active) VALUES (2, 'Плиткорезы', '', 'Плиткорізи', '', 'yes');
INSERT INTO new_tehnorent.category (p_id, name, seo, ua_name, ua_seo, active) VALUES (2, 'Швонарезы', '', 'Швонарізи', '', 'yes');
INSERT INTO new_tehnorent.category (p_id, name, seo, ua_name, ua_seo, active) VALUES (1, 'Компрессорные, сварочные и монтажные инструменты ', '', 'Компресорні, зварювальні та монтажні інструменти', '', 'yes');
INSERT INTO new_tehnorent.category (p_id, name, seo, ua_name, ua_seo, active) VALUES (17, 'Сварочные аппараты ', '', 'Зварювальні апарати', '', 'yes');
INSERT INTO new_tehnorent.category (p_id, name, seo, ua_name, ua_seo, active) VALUES (17, 'Компрессоры', '', 'Компресори', '', 'yes');
INSERT INTO new_tehnorent.category (p_id, name, seo, ua_name, ua_seo, active) VALUES (17, 'Краскопульты', '', 'Фарбопульти', '', 'yes');
INSERT INTO new_tehnorent.category (p_id, name, seo, ua_name, ua_seo, active) VALUES (1, 'Фен строительный', '', 'Фен будівельний', '', 'no');
INSERT INTO new_tehnorent.category (p_id, name, seo, ua_name, ua_seo, active) VALUES (17, 'Паяльники для труб', '', 'Паяльники для труб', '', 'yes');
INSERT INTO new_tehnorent.category (p_id, name, seo, ua_name, ua_seo, active) VALUES (1, 'Ударно - вращательные инструменты', '', 'Ударно - обертальні інструменти', '', 'yes');
INSERT INTO new_tehnorent.category (p_id, name, seo, ua_name, ua_seo, active) VALUES (23, 'Дрели  ударные', '', 'Дрилі ударні', '', 'yes');
INSERT INTO new_tehnorent.category (p_id, name, seo, ua_name, ua_seo, active) VALUES (23, 'Перфораторы', '', 'Перфоратори', '', 'yes');
INSERT INTO new_tehnorent.category (p_id, name, seo, ua_name, ua_seo, active) VALUES (23, 'Шуруповерты', '', 'Шурупуверти', '', 'yes');
INSERT INTO new_tehnorent.category (p_id, name, seo, ua_name, ua_seo, active) VALUES (23, 'Отбойные  молотки', '', 'Відбійні молотки', '', 'yes');
INSERT INTO new_tehnorent.category (p_id, name, seo, ua_name, ua_seo, active) VALUES (23, 'Фрезера', '', 'Фрезери', '', 'yes');
INSERT INTO new_tehnorent.category (p_id, name, seo, ua_name, ua_seo, active) VALUES (23, 'Гвоздезабиватели', '', 'Цвяхозабивачі', '', 'yes');
INSERT INTO new_tehnorent.category (p_id, name, seo, ua_name, ua_seo, active) VALUES (23, 'Гайковерты', '', 'Гайковерти', '', 'yes');
INSERT INTO new_tehnorent.category (p_id, name, seo, ua_name, ua_seo, active) VALUES (1, 'Строительные машины и станки', '', 'Будівельні машини і верстати', '', 'yes');
INSERT INTO new_tehnorent.category (p_id, name, seo, ua_name, ua_seo, active) VALUES (31, 'Виброплиты', '', 'Віброплити', '', 'yes');
INSERT INTO new_tehnorent.category (p_id, name, seo, ua_name, ua_seo, active) VALUES (31, 'Вибротрамбовки', '', 'Вібротрамбовки', '', 'yes');
INSERT INTO new_tehnorent.category (p_id, name, seo, ua_name, ua_seo, active) VALUES (31, 'Генераторы', '', 'Генератори', '', 'yes');
INSERT INTO new_tehnorent.category (p_id, name, seo, ua_name, ua_seo, active) VALUES (1, 'Клининговая техника', '', 'Клінінгова техніка', '', 'yes');
INSERT INTO new_tehnorent.category (p_id, name, seo, ua_name, ua_seo, active) VALUES (35, 'Моющие пылесосы', '', 'Миючі пилососи', '', 'yes');
INSERT INTO new_tehnorent.category (p_id, name, seo, ua_name, ua_seo, active) VALUES (35, 'Мойки  высокого давления', '', 'Мийки високого тиску', '', 'yes');
INSERT INTO new_tehnorent.category (p_id, name, seo, ua_name, ua_seo, active) VALUES (35, 'Строительные пылесосы', '', 'Будівельні пилососи', '', 'yes');
INSERT INTO new_tehnorent.category (p_id, name, seo, ua_name, ua_seo, active) VALUES (35, 'Пароочистители', '', 'Пароочищувачі', '', 'yes');
INSERT INTO new_tehnorent.category (p_id, name, seo, ua_name, ua_seo, active) VALUES (2, 'Электроножницы по металлу', '', 'Електроножиці по металу', '', 'yes');
INSERT INTO new_tehnorent.category (p_id, name, seo, ua_name, ua_seo, active) VALUES (17, 'Фены строительные', '', 'Фени будівельні', '', 'yes');
INSERT INTO new_tehnorent.category (p_id, name, seo, ua_name, ua_seo, active) VALUES (1, 'Оборудование для дома и сада', '', 'Устаткування для дому та саду', '', 'yes');
INSERT INTO new_tehnorent.category (p_id, name, seo, ua_name, ua_seo, active) VALUES (42, 'Воздуходувки', '', 'Повітродувки', '', 'yes');
INSERT INTO new_tehnorent.category (p_id, name, seo, ua_name, ua_seo, active) VALUES (42, 'Садовые  измельчители веток', '', 'Садові подрібнювачі гілок', '', 'yes');
INSERT INTO new_tehnorent.category (p_id, name, seo, ua_name, ua_seo, active) VALUES (42, 'Ямобуры', '', 'Ямобури', '', 'yes');
INSERT INTO new_tehnorent.category (p_id, name, seo, ua_name, ua_seo, active) VALUES (42, 'Мотобуры', '', 'Мотобури', '', 'yes');
INSERT INTO new_tehnorent.category (p_id, name, seo, ua_name, ua_seo, active) VALUES (42, 'Мотоблоки, культиваторы', '', 'Мотоблоки, культиватори', '', 'yes');
INSERT INTO new_tehnorent.category (p_id, name, seo, ua_name, ua_seo, active) VALUES (42, 'Мотокосы', '', 'Мотокосарки', '', 'yes');
INSERT INTO new_tehnorent.category (p_id, name, seo, ua_name, ua_seo, active) VALUES (42, 'Газонокосилки', '', 'Газонокосарки', '', 'yes');
INSERT INTO new_tehnorent.category (p_id, name, seo, ua_name, ua_seo, active) VALUES (42, 'Садовые пылесосы', '', 'Садові пилососи', '', 'yes');
INSERT INTO new_tehnorent.category (p_id, name, seo, ua_name, ua_seo, active) VALUES (1, 'Измерительная техника', '', 'Вимірювальна техніка', '', 'yes');
INSERT INTO new_tehnorent.category (p_id, name, seo, ua_name, ua_seo, active) VALUES (51, 'Лазерные уровни', '', 'Лазерні рівні', '', 'yes');
INSERT INTO new_tehnorent.category (p_id, name, seo, ua_name, ua_seo, active) VALUES (51, 'Лазерные рулетки', '', 'Лазерні рулетки', '', 'yes');